[package]
name = "rustris-bevy"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.10.2"
strum = "0.28.0"
strum_macros = "0.28.0"
bevy = "0.19.1"
blob = "0.3.0"
linebender_resource_handle = "0.1.1"

[profile.release]
opt-level = "s"     
lto = true          
codegen-units = 1   
panic = "abort"     
strip = true        
